### ISSUE TITLE
Temporarily disable PDF generation in Asciidoctor setup

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/st-lab#39]
The PDF creation with AsciiDoctor/J has a lot of issues which can't be resolved easily.

* For some groups, the PDF creation with AsciiDoctor/J has issues with anchors in tables that result in `Prawn::Errors::CannotFit` exceptions. Building the same document using the latest Ruby `asciidoctor-pdf` gem works, as well as the HTML version. The problem is the `org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16` artifact, which is the most recent version on Maven Central but nevertheless more than a year old. The package probably doesn't contain the latest bugfixes. For this reason I instructed the affected groups to apply [a patch to their `pom.xml`](https://github.com/st-tu-dresden/st-lab/files/2588808/disable-asciidoctor-pdf.patch.txt).
* Moreover, the tool "shines" with excessive memory usage when it tries to embed images, which results in `Heap space` errors for some groups (even with `-Xmx4G` or `-Xmx5G`).
* Last but not least: #7.

What do you think, @odrotbohm? For the CI, it should be possible to call an external cli tool such as `asciidoctor-pdf`.

**Comment by odrotbohm** [comment]
I pinged Dan [on Twitter](https://twitter.com/olivergierke/status/1063478664438910978). Let's see what he says.

**Comment by mojavelinux** [comment]
Thanks for reaching out. I think I can share some information that will help you.

The current release of AsciidoctorJ PDF [1.5.0-alpha.16](https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/jar) does match the latest release of Asciidoctor PDF (which, as you pointed out, hasn't been release in a year). But since AsciidoctorJ PDF recommends an AsciidoctorJ version, you do need to override it to use AsciidoctorJ 1.5.8.1 if you want it to behave exactly like Asciidoctor PDF.

Since there have been a number of bug fixes in Asciidoctor PDF since then (see [CHANGELOG](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/CHANGELOG.adoc#unreleased)), I plan to push out another release fairly soon, which will then be followed by its AsciidoctorJ counterpart. However, it's unlikely to resolve all the issues you mentioned. I'll explain why and what our next move is.

Asciidoctor PDF was designed for making PDF documents that adhere to a rather typical layout. While the theme integration does provide a fair number of properties to customize, they're mostly focused on style (in the classic sense), not layout. In other words, there are hard limits. The main issue is that the underlying PDF library is write only. In order to do any dimension computation, it's necessary to use a write ahead strategy (aka prerendering). Background colors are especially problematic since the engine has to prerender the whole block (and it's children) to know how much to paint behind it. This costs a lot of time and memory. There's a lot of this going on.

Recognizing the limitations in the design of Asciidoctor PDF / Prawn, I've decided to take a step back and rethink our PDF strategy. We need something that won't be so costly and will allow us to style and layout the document with more freedom. A promising solution is to leverage the headless browser libraries (like [puppeteer](https://github.com/GoogleChrome/puppeteer)) with the help of shims to prepare the page and distill it to PDF. I'll be announcing the plan in the Asciidoctor mailinglist later this week.

...and I'm not saying you shouldn't invoke `asciidoctor-pdf` from the CLI. That's always an option. AsciidoctorJ PDF is a repackaging / convenience for people who want it. If it isn't convenient, don't use it.

So if you can hold on making PDF using Asciidoctor PDF for a little while longer, we have something better coming.

**Comment by odrotbohm** [comment]
I've removed the PDF generation for now but have followed Dan's advice to upgrade to the latest versions.
