### ISSUE TITLE
Images missing after rendering adoc to pdf/html 

### ISSUE THREAD

**Issue by SvenSeemann** [st-tu-dresden/st-lab#7]

**Comment by olivergierke** [comment]
Can you elaborate a bit on what's not working (like setup, what happens, what's expected to happen)?

**Comment by martinmo** [comment]
I've looked into this and can say this is a real mess. I couldn't figure out a plugin configuration that works for both the html and pdf outputs and allows referencing images in *.adoc files in subdirectories. 

I strongly suspect that this doesn't work anymore with the asciidoctor plugin default setup because we set `preserveDirectories` to `true` (see #21 and #8).

### Current Setup

With the current setup, the following kinda works, provided if one puts the images below `src/main/asciidoc/images` (the default `imagesDir` setting of the asciidoctor plugin):

```
src/main/asciidoc
├── first.adoc       <- reference via `image:foo.png[]` works in PDF and HTML
├── images
│   └── foo.png
└── subdir
    └── second.adoc  <- reference via `image:foo.png[]` only works for PDF :(
```

Btw: In both cases, the IntelliJ preview cannot show the image.

### Trial: Setting imagesDir to .

I tried setting `imagesDir` to `.`, in order to be able to put the image beside the *.adoc files, which means having a structure like:

```
src/main/asciidoc
├── first.adoc
├── first.png
└── subdir
    ├── second.adoc
    └── second.png
```

This works with HTML **and** IntelliJ. Unfortunately, this breaks the PDF output unless the image files are duplicated in the `src/main/asciidoc/images` dir.

**Comment by martinmo** [comment]
Oh, and to clarify: the images are always present on the file system level (in the `target` folders and ZIP files), **but** not always included in the PDF or HTML files.
